### ISSUE TITLE
On-Floor Status Vote

### ISSUE THREAD

**Issue by bmbowdish** [ComputerScienceHouse/Constitution#74]
Check one:
- [X] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
During our Introductory Evaluations meeting we seem to automatically go for an On-Floor Status vote. The constitution does not mandate this, and I think we should talk about whether or not we should just stop doing it or an amendment needs to be added. I think house is generally in agreement that the On-Floor Status vote is a waste of time usually. 

Is this how it has always been? Are there any Nth years that remember it being different?

**Comment by VictoriaWeaver** [comment]
Unless the prospective member states one way or another, it's up to the Evals Director whether or not they want to hold the vote for on-floor or not.  The constitution states that a member can request to be brought up for on-floor status at any time.  When I was Evals, I operated under the assumption that if a person becomes an intro member, then they would likely want on-floor status anyway (I was also following precedent).

It is perfectly within the right of the Evals Director to ask the prospective member if they want to be brought up at all for on-floor status.  If the prospective member's desire is unknown, it is also within Evals's right to ask the room at the time of the vote if they want to consider on floor status.  If the general consensus is no, then the vote doesn't have to happen.  

Generally the best course of action would be to either hold the vote automatically as we currently do (unless the prospective member states otherwise), or to ask the prospective member if they want to be brought up.

**Comment by JDrit** [comment]
Nth year here, we have done this for as long as I can remember. Since there is absolutely no reason for not wanting to be an on-floor member, I would suggest just toss it up to Evals discretion.

**Comment by liam-middlebrook** [comment]
I don't think this needs to be explicitly forbidden. Right now the way that it is worded allows for us to operate in the way we've done since @eatnumber1 was a freshman. I don't see a compelling reason to change this.
